import Database from 'better-sqlite3';
import bcrypt from 'bcryptjs';
import path from 'node:path';

const databasePath = process.env.DATABASE_PATH || (process.env.VERCEL === '1' ? '/tmp/chinhthuc.sqlite' : path.resolve(process.cwd(), 'chinhthuc.sqlite'));
export const db = new Database(databasePath, { readonly: false });
if (process.env.VERCEL !== '1') db.pragma('journal_mode = WAL');
db.exec(`
  CREATE TABLE IF NOT EXISTS users (id INTEGER PRIMARY KEY AUTOINCREMENT, name TEXT NOT NULL, email TEXT UNIQUE NOT NULL, password_hash TEXT NOT NULL, role TEXT NOT NULL DEFAULT 'user', created_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP);
  CREATE TABLE IF NOT EXISTS categories (id INTEGER PRIMARY KEY AUTOINCREMENT, name TEXT NOT NULL, slug TEXT UNIQUE NOT NULL, parent_id INTEGER, image TEXT DEFAULT '', sort_order INTEGER NOT NULL DEFAULT 0, published INTEGER NOT NULL DEFAULT 1, FOREIGN KEY(parent_id) REFERENCES categories(id));
  CREATE TABLE IF NOT EXISTS products (id TEXT PRIMARY KEY, name TEXT NOT NULL, slug TEXT UNIQUE NOT NULL, category TEXT NOT NULL, category_id INTEGER, sku TEXT DEFAULT '', brand TEXT DEFAULT '', image TEXT NOT NULL, gallery TEXT NOT NULL DEFAULT '[]', specs TEXT NOT NULL DEFAULT '[]', description TEXT NOT NULL, short_description TEXT DEFAULT '', video_url TEXT DEFAULT '', documents TEXT NOT NULL DEFAULT '[]', badges TEXT NOT NULL DEFAULT '[]', price_mode TEXT NOT NULL DEFAULT 'contact', price REAL, featured INTEGER NOT NULL DEFAULT 0, bestseller INTEGER NOT NULL DEFAULT 0, published INTEGER NOT NULL DEFAULT 1, seo_title TEXT DEFAULT '', seo_description TEXT DEFAULT '', highlights TEXT NOT NULL DEFAULT '[]', applications TEXT NOT NULL DEFAULT '[]', created_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP, FOREIGN KEY(category_id) REFERENCES categories(id));
  CREATE TABLE IF NOT EXISTS posts (id INTEGER PRIMARY KEY AUTOINCREMENT, title TEXT NOT NULL, slug TEXT UNIQUE NOT NULL, type TEXT NOT NULL DEFAULT 'news', excerpt TEXT DEFAULT '', content TEXT NOT NULL, cover_image TEXT DEFAULT '', status TEXT NOT NULL DEFAULT 'draft', seo_title TEXT DEFAULT '', seo_description TEXT DEFAULT '', published_at TEXT, created_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP);
   CREATE TABLE IF NOT EXISTS projects (id INTEGER PRIMARY KEY AUTOINCREMENT, title TEXT NOT NULL, slug TEXT UNIQUE NOT NULL, industry TEXT NOT NULL, cover_image TEXT NOT NULL, gallery TEXT NOT NULL DEFAULT '[]', summary TEXT NOT NULL, challenge TEXT NOT NULL DEFAULT '', solution TEXT NOT NULL DEFAULT '', result TEXT NOT NULL DEFAULT '', related_product_ids TEXT NOT NULL DEFAULT '[]', published INTEGER NOT NULL DEFAULT 0, created_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP);
   CREATE TABLE IF NOT EXISTS sliders (id INTEGER PRIMARY KEY AUTOINCREMENT, title TEXT NOT NULL DEFAULT '', image TEXT NOT NULL, link TEXT DEFAULT '#/san-pham', sort_order INTEGER NOT NULL DEFAULT 0, published INTEGER NOT NULL DEFAULT 1, created_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP);
  CREATE TABLE IF NOT EXISTS pages (id INTEGER PRIMARY KEY AUTOINCREMENT, title TEXT NOT NULL, slug TEXT UNIQUE NOT NULL, content TEXT NOT NULL, status TEXT NOT NULL DEFAULT 'published', seo_title TEXT DEFAULT '', seo_description TEXT DEFAULT '', updated_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP);
  CREATE TABLE IF NOT EXISTS site_settings (key TEXT PRIMARY KEY, value TEXT NOT NULL);
  CREATE TABLE IF NOT EXISTS audit_logs (id INTEGER PRIMARY KEY AUTOINCREMENT, user_id INTEGER, action TEXT NOT NULL, resource TEXT NOT NULL, resource_id TEXT, metadata TEXT DEFAULT '{}', created_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP, FOREIGN KEY(user_id) REFERENCES users(id));
  CREATE TABLE IF NOT EXISTS quote_requests (id INTEGER PRIMARY KEY AUTOINCREMENT, user_id INTEGER, name TEXT NOT NULL, email TEXT NOT NULL, phone TEXT, message TEXT NOT NULL, status TEXT NOT NULL DEFAULT 'new', internal_note TEXT DEFAULT '', assignee_id INTEGER, created_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP, FOREIGN KEY(user_id) REFERENCES users(id), FOREIGN KEY(assignee_id) REFERENCES users(id));
  CREATE TABLE IF NOT EXISTS quote_items (id INTEGER PRIMARY KEY AUTOINCREMENT, request_id INTEGER NOT NULL, product_id TEXT NOT NULL, quantity INTEGER NOT NULL DEFAULT 1, FOREIGN KEY(request_id) REFERENCES quote_requests(id), FOREIGN KEY(product_id) REFERENCES products(id));
`);
try { db.exec("ALTER TABLE products ADD COLUMN category_id INTEGER; ALTER TABLE products ADD COLUMN gallery TEXT NOT NULL DEFAULT '[]'; ALTER TABLE products ADD COLUMN specs TEXT NOT NULL DEFAULT '[]'; ALTER TABLE products ADD COLUMN short_description TEXT DEFAULT ''; ALTER TABLE products ADD COLUMN video_url TEXT DEFAULT ''; ALTER TABLE products ADD COLUMN price_mode TEXT NOT NULL DEFAULT 'contact'; ALTER TABLE products ADD COLUMN price REAL; ALTER TABLE products ADD COLUMN featured INTEGER NOT NULL DEFAULT 0; ALTER TABLE products ADD COLUMN bestseller INTEGER NOT NULL DEFAULT 0; ALTER TABLE products ADD COLUMN seo_title TEXT DEFAULT ''; ALTER TABLE products ADD COLUMN seo_description TEXT DEFAULT '';"); } catch { /* Existing installations already have the extended columns. */ }
const adminEmail = process.env.ADMIN_EMAIL || 'admin@chinhthuc.local';
const adminPassword = process.env.ADMIN_PASSWORD || 'ChangeMe123!';
const existing = db.prepare('SELECT id FROM users WHERE email = ?').get(adminEmail);
if (!existing) db.prepare('INSERT INTO users (name,email,password_hash,role) VALUES (?,?,?,?)').run('Quản trị viên', adminEmail, bcrypt.hashSync(adminPassword, 12), 'admin');
const seedProducts = [
  ['jwei', 'Máy Cắt Kỹ Thuật Số JWEI', 'may-cat-ky-thuat-so-jwei', 'Máy cắt KTS', 'https://chinhthucmayktscnc.com/wp-content/uploads/2025/10/jwei-546x800.jpg', 'Giải pháp cắt kỹ thuật số chính xác cho sản xuất bao bì, quảng cáo và công nghiệp.'],
  ['ckun', 'MÁY CẮT KỸ THUẬT SỐ CKUN', 'may-cat-mau-1', 'Máy cắt KTS', 'https://chinhthucmayktscnc.com/wp-content/uploads/2025/09/1-533x400.jpg', 'Máy cắt tự động hiệu suất cao, vận hành ổn định và tối ưu chi phí đầu tư.'],
  ['emma', 'Lưỡi dao cắt EMMA', 'may-cat-kts-pk-10', 'Lưỡi dao', 'https://chinhthucmayktscnc.com/wp-content/uploads/2025/09/image-1752464916687-796864111-IMG_202406178_101930369-400x400.png', 'Lưỡi dao thay thế sắc bén, bền bỉ cho nhiều dòng máy cắt kỹ thuật số.'],
  ['cnc', 'Lưỡi dao rung cho máy KTS CNC', 'may-cat-kts-pk-08', 'Lưỡi dao', 'https://chinhthucmayktscnc.com/wp-content/uploads/2025/09/image-1752493017788-633936787-IMG_20240422_123933-300x400.jpg', 'Phụ kiện dao rung tương thích AOKE, CKUN, JWEI, ICHO và nhiều dòng máy khác.'],
  ['aoke', 'Máy cắt mẫu AOKE', 'may-cat-kts-pk-07', 'Máy cắt KTS', 'https://chinhthucmayktscnc.com/wp-content/uploads/2025/09/aoke-744x400.jpg', 'Thiết bị cắt mẫu linh hoạt cho nhu cầu gia công đa vật liệu.'],
  ['head', 'Đầu dao rung máy AOKE, CKUN, JWEI, ICHO...', 'dau-dao-pk-05', 'Đầu dao máy cắt KTS', 'https://chinhthucmayktscnc.com/wp-content/uploads/2025/09/2-300x400.jpg', 'Đầu dao chính hãng và linh kiện thay thế cho máy cắt kỹ thuật số.'],
  ['felt', 'Thảm nỉ máy cắt kỹ thuật số', 'luoi-dao-pk-10', 'Thảm nỉ', 'https://chinhthucmayktscnc.com/wp-content/uploads/2025/09/tham1-400x400.jpg', 'Thảm nỉ chuyên dụng giúp bảo vệ bàn máy và giữ độ ổn định khi cắt.'],
  ['blade-v', 'LƯỠI DAO PHAY, LƯỠI DAO V', 'dau-dao-pk-05-2', 'Lưỡi dao', 'https://chinhthucmayktscnc.com/wp-content/uploads/2025/09/dao-phay-402x400.jpg', 'Dòng dao phay và dao V cho các ứng dụng tạo rãnh, bế và gia công chính xác.'],
] as const;
const defaultCategories = ['Máy cắt KTS', 'Lưỡi dao', 'Thảm nỉ', 'Đầu dao máy cắt KTS'];
const categoryInsert = db.prepare('INSERT OR IGNORE INTO categories (name,slug) VALUES (?,?)');
defaultCategories.forEach(name => categoryInsert.run(name, name.toLowerCase().normalize('NFD').replace(/[\u0300-\u036f]/g, '').replace(/đ/g, 'd').replace(/[^a-z0-9]+/g, '-').replace(/^-|-$/g, '')));
const sliderSeed = db.prepare('INSERT OR IGNORE INTO sliders (id,title,image,link,sort_order,published) VALUES (?,?,?,?,?,?)'); sliderSeed.run(1, 'Giải pháp cắt chính xác', 'https://chinhthucmayktscnc.com/wp-content/uploads/2025/09/banner-1-1400x609.png', '#/san-pham', 0, 1);
const settingsSeed = db.prepare('INSERT OR IGNORE INTO site_settings (key,value) VALUES (?,?)'); [['company_name','CÔNG TY TNHH CHÍNH THỰC'],['hotline','0916 412 896'],['email','chinhthucmaycnc@gmail.com'],['address','Bình Dương, Việt Nam'],['facebook','https://web.facebook.com/cong.ty.chinh.thuc/'],['logo_url',''],['favicon_url',''],['zalo','https://zalo.me/0916412896']].forEach(([key,value]) => settingsSeed.run(key,value));
const aboutSeed = db.prepare('INSERT OR IGNORE INTO pages (title,slug,content,status) VALUES (?,?,?,?)'); aboutSeed.run('Kinh nghiệm tạo nên khác biệt.','gioi-thieu','<h2>Đơn vị đồng hành kỹ thuật cho sản xuất Việt.</h2><p>CHÍNH THỰC là đơn vị chuyên cung cấp máy cắt kỹ thuật số, lưỡi dao và phụ kiện CNC. Với hơn 12 năm kinh nghiệm, đội ngũ kỹ thuật am hiểu thiết bị giúp khách hàng chọn đúng giải pháp và vận hành hiệu quả.</p>','published');
const postSeed = db.prepare('INSERT OR IGNORE INTO posts (title,slug,type,excerpt,content,status,published_at) VALUES (?,?,?,?,?,?,?)'); postSeed.run('Sản xuất và gia công tùy chỉnh với máy cắt kỹ thuật số','san-xuat-va-gia-cong-tuy-chinh','news','Khám phá cách tối ưu quy trình cắt, giảm hao phí vật liệu và tăng độ chính xác.','<p>Khám phá cách tối ưu quy trình cắt, giảm hao phí vật liệu và tăng độ chính xác.</p>','published',new Date().toISOString()); postSeed.run('Lưỡi dao công nghiệp phục vụ ngành thực phẩm và bao bì','luoi-dao-cong-nghiep','news','Những lưu ý khi lựa chọn lưỡi dao phù hợp với từng vật liệu.','<p>Những lưu ý khi lựa chọn lưỡi dao phù hợp với từng vật liệu.</p>','published',new Date().toISOString());
const productCount = db.prepare('SELECT COUNT(*) as count FROM products').get() as { count: number };
if (productCount.count === 0) { const insert = db.prepare('INSERT INTO products (id,name,slug,category,image,description) VALUES (?,?,?,?,?,?)'); const seed = db.transaction(() => seedProducts.forEach(product => insert.run(...product))); seed(); }

const userTable = db.prepare("SELECT sql FROM sqlite_master WHERE type = 'table' AND name = 'users'").get() as { sql?: string } | undefined;
if (userTable?.sql?.includes("CHECK(role IN")) {
  db.exec('ALTER TABLE users RENAME TO users_legacy; CREATE TABLE users (id INTEGER PRIMARY KEY AUTOINCREMENT, name TEXT NOT NULL, email TEXT UNIQUE NOT NULL, password_hash TEXT NOT NULL, role TEXT NOT NULL DEFAULT \'user\', created_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP); INSERT INTO users (id,name,email,password_hash,role,created_at) SELECT id,name,email,password_hash,role,created_at FROM users_legacy; DROP TABLE users_legacy;');
}
for (const statement of ["ALTER TABLE quote_requests ADD COLUMN internal_note TEXT DEFAULT ''", 'ALTER TABLE quote_requests ADD COLUMN assignee_id INTEGER', "ALTER TABLE products ADD COLUMN sku TEXT DEFAULT ''", "ALTER TABLE products ADD COLUMN brand TEXT DEFAULT ''", "ALTER TABLE products ADD COLUMN documents TEXT NOT NULL DEFAULT '[]'", "ALTER TABLE products ADD COLUMN badges TEXT NOT NULL DEFAULT '[]'", "ALTER TABLE products ADD COLUMN highlights TEXT NOT NULL DEFAULT '[]'", "ALTER TABLE products ADD COLUMN applications TEXT NOT NULL DEFAULT '[]'"]) { try { db.exec(statement); } catch { /* Column already exists. */ } }
const legacyForeignTables = db.prepare("SELECT name,sql FROM sqlite_master WHERE type = 'table' AND sql LIKE '%users_legacy%'").all() as Array<{ name: string; sql: string }>;
if (legacyForeignTables.some(table => table.name === 'quote_requests')) {
  db.pragma('foreign_keys = OFF');
  db.exec('DROP TABLE IF EXISTS quote_requests_fixed;');
  db.exec(`CREATE TABLE quote_requests_fixed (id INTEGER PRIMARY KEY AUTOINCREMENT, user_id INTEGER, name TEXT NOT NULL, email TEXT NOT NULL, phone TEXT, message TEXT NOT NULL, status TEXT NOT NULL DEFAULT 'new', internal_note TEXT DEFAULT '', assignee_id INTEGER, created_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP, FOREIGN KEY(user_id) REFERENCES users(id), FOREIGN KEY(assignee_id) REFERENCES users(id)); INSERT INTO quote_requests_fixed (id,user_id,name,email,phone,message,status,internal_note,assignee_id,created_at) SELECT id,user_id,name,email,phone,message,status,internal_note,assignee_id,created_at FROM quote_requests; DROP TABLE quote_requests; ALTER TABLE quote_requests_fixed RENAME TO quote_requests;`);
}
if (legacyForeignTables.some(table => table.name === 'audit_logs')) {
  db.pragma('foreign_keys = OFF');
  db.exec('DROP TABLE IF EXISTS audit_logs_fixed;');
  db.exec(`CREATE TABLE audit_logs_fixed (id INTEGER PRIMARY KEY AUTOINCREMENT, user_id INTEGER, action TEXT NOT NULL, resource TEXT NOT NULL, resource_id TEXT, metadata TEXT DEFAULT '{}', created_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP, FOREIGN KEY(user_id) REFERENCES users(id)); INSERT INTO audit_logs_fixed (id,user_id,action,resource,resource_id,metadata,created_at) SELECT id,user_id,action,resource,resource_id,metadata,created_at FROM audit_logs; DROP TABLE audit_logs; ALTER TABLE audit_logs_fixed RENAME TO audit_logs;`);
}
db.pragma('foreign_keys = ON');

export type User = { id: number; name: string; email: string; role: 'user' | 'admin' | 'editor' | 'sales' };
