import { ChangeEvent, useEffect, useState } from 'react';

type SpecModel = { model: string; values: Record<string, string> };

const blank = (): SpecModel => ({ model: '', values: { 'Thông số': '' } });
const parseCsv = (text: string): SpecModel[] => { const lines = text.trim().split(/\r?\n/).filter(Boolean).map(line => line.split(',').map(value => value.trim())); if (lines.length < 2) return []; const headers = lines[0]; return lines.slice(1).map(row => ({ model: row[0] || '', values: Object.fromEntries(headers.slice(1).map((header, index) => [header, row[index + 1] || ''])) })); };

export function SpecsEditor({ value, onChange }: { value: string; onChange: (value: string) => void }) {
  const [models, setModels] = useState<SpecModel[]>([]); const [error, setError] = useState('');
  useEffect(() => { try { const parsed = JSON.parse(value || '[]'); setModels(Array.isArray(parsed) ? parsed.map(item => ({ model: item.model || '', values: item.values || {} })) : []); } catch { setModels([]); } }, [value]);
  const emit = (next: SpecModel[]) => { setModels(next); onChange(JSON.stringify(next)); };
  const updateModel = (index: number, model: SpecModel) => emit(models.map((item, row) => row === index ? model : item));
  const addRow = (index: number) => { const current = models[index] || blank(); updateModel(index, { ...current, values: { ...current.values, 'Thông số mới': '' } }); };
  const importFile = (event: ChangeEvent<HTMLInputElement>) => { const file = event.target.files?.[0]; if (!file) return; const reader = new FileReader(); reader.onload = () => { try { const text = String(reader.result || ''); const parsed = file.name.toLowerCase().endsWith('.json') ? JSON.parse(text) : parseCsv(text); if (!Array.isArray(parsed) || !parsed.length) throw new Error('File không có dữ liệu hợp lệ.'); const normalized = parsed.map(item => ({ model: item.model || '', values: item.values || Object.fromEntries(Object.entries(item).filter(([key]) => key !== 'model').map(([key, val]) => [key, String(val)])) })); emit(normalized); setError(''); } catch (e) { setError((e as Error).message); } }; reader.readAsText(file); event.target.value = ''; };
  return <div className="specs-editor"><div className="specs-editor-head"><div><b>Bảng thông số kỹ thuật</b><small>Mỗi dòng là một model/mã máy.</small></div><div className="specs-tools"><label>Nhập CSV/JSON<input type="file" accept=".csv,.json,application/json,text/csv" onChange={importFile}/></label><button type="button" onClick={() => emit([...models, blank()])}>+ Thêm model</button></div></div>{error && <p className="form-error">{error}</p>}{models.length === 0 ? <div className="specs-empty">Chưa có model. Bấm “+ Thêm model” hoặc nhập file.</div> : models.map((item, index) => <div className="spec-model-editor" key={index}><div className="spec-model-bar"><input placeholder="Mã model: QD2516" value={item.model} onChange={event => updateModel(index, { ...item, model: event.target.value })}/><button type="button" onClick={() => emit(models.filter((_, row) => row !== index))}>Xóa model</button></div>{Object.entries(item.values).map(([key, val]) => <div className="spec-value-row" key={key}><input value={key} aria-label="Tên thông số" onChange={event => { const values = { ...item.values }; const value = values[key]; delete values[key]; values[event.target.value] = value; updateModel(index, { ...item, values }); }}/><input value={val} aria-label="Giá trị thông số" placeholder="Giá trị" onChange={event => updateModel(index, { ...item, values: { ...item.values, [key]: event.target.value } })}/><button type="button" onClick={() => { const values = { ...item.values }; delete values[key]; updateModel(index, { ...item, values }); }}>×</button></div>)}<button className="spec-add-row" type="button" onClick={() => addRow(index)}>+ Thêm dòng thông số</button></div>)}</div>;
}
